os:
  - linux
  - osx	

language: cpp

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd    build
  - cmake ..

script:
  - make
  - cd ..
  - mkdir TestBuild
  - cd TestBuild
  - cmake ../Testing
  - make 
  - make test




